#!/bin/bash

case $(file --mime-type "$1" -bL) in
    text/*|application/json)
        bat --paging=never --style=plain --terminal-width $(($2-5)) -f "$1" || true ;;
    application/zip)
        unzip -l "$1" ;;
    *)
        file "$1" -bL ;;
esac
