#!/bin/bash

#case "$1" in
#    *.tgz|*.tar.gz) tar tzf "$1";;
#    *.tar.bz2|*.tbz2) tar tjf "$1";;
#    *.tar.txz|*.txz) xz --list "$1";;
#    *.tar) tar tf "$1";;
#    *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1";;
#    *.rar) unrar l "$1";;
#    *.7z) 7z l "$1";;
#    *.bmp|*.jpg|*.JPG|*.jpeg|*.png|*.xpm|*.webp) mediainfo "$1";;
#    *.avi|*.mp4|*.wmv|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.mov|*.webm|*.m4v|*.qt|*.divx|*.mp3) mediainfo "$1";;
#    *.pdf|*.odf|*.odg) file -b "$1";;
#    *.epub) epub2txt "$1";;
#    *) bat --paging=never --style=plain --terminal-width $(($2-5)) -f "$1" || true;;
#esac

case $(file --mime-type "$1" -bL) in
    text/*|application/json)
        bat --paging=never --style=plain --terminal-width $(($2-5)) -f "$1" || true ;;
    application/zip)
        unzip -l "$1" ;;
    *)
        file "$1" -bL ;;
esac
