#!/bin/bash

options=""

(mount | grep /media/NAS/Media &> /dev/null) && options="Unmount NAS/Media" || options="Mount NAS/Media"
(mount | grep remote: &> /dev/null) && options="${options}\nUnmount GDrive" || options="${options}\nMount GDrive"

choice=$(echo -e "${options}" | fuzzel --dmenu --lines 3 -p "Mounter") 

case $choice in
    "Mount NAS/Media")    mount /media/NAS/Media &>> ~/mount.log
                          notify-send --app-name="Mounter" "NAS/Media mounted" ;; 

    "Unmount NAS/Media")  umount /media/NAS/Media &>> ~/mount.log
                          notify-send --app-name="Mounter" "NAS/Media unmounted" ;; 

    "Mount GDrive")       rclone mount remote: ~/GDrive \
                           --daemon \
                           --exclude "/Fotky/**" \
                           --vfs-cache-mode full \
                           --vfs-read-chunk-size=64k \
                           --cache-dir /tmp/rclone \
                           --no-checksum \
                           --no-modtime \
                           --no-seek \
                           &>> ~/mount.log \
                          && notify-send --app-name="Mounter" "Google Drive mounted" \
                          || notify-send --app-name="Mounter" "Could not mount Google Drive" ;; 

    "Unmount GDrive")     fusermount -u ~/GDrive &>> ~/mount.log \
                          && notify-send --app-name="Mounter" "Google Drive unmounted" \
                          || notify-send --app-name="Mounter" "Could not unmount Google Drive" ;; 
esac 
