#!/bin/bash

echo -e " \
 + F1              \t Show this help \n \
 + Space           \t Application menu \n \
 + q               \t Close window \n \
 + Enter           \t Terminal \n \
 + Ctrl + b        \t Internet browser \n \
 + Ctrl + e        \t File manager \n \
 + Ctrl + o        \t Select audio/video output \n \
 + Ctrl + w        \t Web Apps \n \
 + /               \t Yazi file manager \n \
 + l               \t Lock screen \n \
 + f               \t Toggle fullscreen \n \
 + m               \t Mount/Unmount USB drive \n \
 + .               \t Edit config files \n \
 + Esc             \t System monitor \n \
 + Shift + q       \t Power menu \n \
 + Shift + b       \t Restart waybar \n \
 + Shift + Space   \t Toggle floating \n \
PrintScreen         \t Screenshot (full screen) \n \
Shift + PrintScreen \t Screenshot (area) \n \
" | fuzzel --dmenu --lines 15 --width 55 -p "Sway keybindings"
