#!/usr/bin/env bash

choice=$(echo -e " WhatsApp\n󱜸 ChatGPT" | sort | fuzzel --dmenu -p "Select webapp") 

case $choice in
    "󱜸 ChatGPT")            brave --app="https://chat.openai.com" ;;
    " WhatsApp")           brave --app="https://web.whatsapp.com" ;;
esac
