#!/bin/bash

choice=$(echo -e "WhatsApp\nChatGPT" | sort | fuzzel --dmenu -p "Select webapp") 

case $choice in
    ChatGPT)            brave --app="https://chat.openai.com" ;;
    WhatsApp)           brave --app="https://web.whatsapp.com" ;;
esac
