#!/usr/bin/env bash

swayidle -w \
timeout 30 'if pgrep -x swaylock ; then mmsg dispatch disable_monitor; fi' resume 'mmsg dispatch enable_monitor' \
timeout 300 'if pgrep -x swaylock ; then mmsg dispatch disable_monitor; else swaylock -f && mmsg dispatch disable_monitor; fi' resume 'mmsg dispatch enable_monitor' \
timeout 1800 'systemctl suspend' resume 'mmsg dispatch enable_monitor' \
before-sleep 'swaylock -f'
