#!/bin/bash

options=""

(mount | grep /media/NAS/Media &> /dev/null) && options="Unmount NAS/Media" || options="Mount NAS/Media"
(mount | grep remote: &> /dev/null) && options="${options}|Unmount GDrive" || options="${options}|Mount GDrive"

choice=$(echo -n "${options}" | rofi -sep '|' -dmenu -p "Mounter" -no-fixed-num-lines)

case $choice in
    "Mount NAS/Media")    mount /media/NAS/Media &>> ~/mount.log
                          notify-send "NAS/Media mounted" ;; 

    "Unmount NAS/Media")  umount /media/NAS/Media &>> ~/mount.log
                          notify-send "NAS/Media unmounted" ;; 

    "Mount GDrive")       [ rclone mount --daemon remote: ~/GDrive --exclude "/Fotky/**" --vfs-cache-mode writes &>> ~/mount.log ] \
                          && notify-send "Google Drive mounted" \
                          || notify-send "Could not mount Google Drive" ;; 

    "Unmount GDrive")     [ fusermount -u ~/GDrive &>> ~/mount.log ] \
                          && notify-send "Google Drive unmounted" \
                          || notify-send "Could not unmount Google Drive" ;; 
esac 
