runtime default.vimrc

"Color scheme settings
colorscheme catppuccin_mocha
let g:lightline = {'colorscheme' : 'catppuccin_mocha'}

"Red undercurl color for spell check
hi SpellBad cterm=undercurl ctermbg=NONE ctermul=red gui=undercurl guisp=red
hi Comment cterm=italic
hi Normal guibg=NONE
hi NormalFloat guibg=NONE
hi NonText guibg=NONE
