#!/usr/bin/env bash

choice=$(echo -e " WhatsApp\n󱜸 ChatGPT\n󰈙 Google Docs\n󰧷 Google Sheets\n󰛜 Google Keep\n󰝆 Netflix" | sort | fuzzel --dmenu -p "Select webapp") 

case $choice in
    "󱜸 ChatGPT")            brave --app="https://chat.openai.com" ;;
    " WhatsApp")           brave --app="https://web.whatsapp.com" ;;
    "󰈙 Google Docs")        brave --app="https://docs.google.com/document/u/0/" ;;
    "󰧷 Google Sheets")      brave --app="https://docs.google.com/spreadsheets/u/0/?ec=wgc-sheets-globalnav-goto" ;;
    "󰛜 Google Keep")        brave --app="https://keep.google.com" ;;
    "󰝆 Netflix")            brave --app="https://www.netflix.com" ;;
esac
