#!/bin/bash

choice=$(echo -e "󰍃 Log out\n󰜉 Reboot\n󰐥 Shut down" | fuzzel --dmenu --lines 4 -p "Power menu" )

case $choice in
    "󰍃 Log out")    systemctl --user stop niri.service ;;
    "󰜉 Reboot")     systemctl reboot ;; 
    "󰐥 Shut down")  systemctl poweroff ;;
esac
