#!/usr/bin/env bash

app_id=$(niri msg -j windows | jq '.[] | select(.app_id == "yazi") | .id')

[[ -n $app_id ]] && niri msg action focus-window --id $app_id || niri msg action spawn-sh -- "footclient --app-id yazi bash -ic 'yazi'"
